//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTorgovyAutomat.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coins()
        {
            this.VendingMachinesCoins = new HashSet<VendingMachinesCoins>();
        }
    
        public int id { get; set; }
        public int CoinsNaminale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachinesCoins> VendingMachinesCoins { get; set; }
    }
}
